### ISSUE TITLE
Topics carried over from open-source-ideas repo

### ISSUE THREAD

**Issue by FredrikAugust** [open-source-ideas/meta#1]
- [x] [Add programming language tags Open Source Ideas Initiative #76](https://github.com/open-source-ideas/open-source-ideas/issues/76)
- [x] [Migrate from GitHub #67](https://github.com/open-source-ideas/open-source-ideas/issues/67)
- [x] [Rework open-source-ideas website #59](https://github.com/open-source-ideas/open-source-ideas/issues/59)
- [x] [Develop a criteria for work and difficulty estimation #55](https://github.com/open-source-ideas/open-source-ideas/issues/55)

**Comment by mikaelbr** [comment]
Ah. Great. Was just about to move these over. 🎉
